# Generated by Django 5.1.3 on 2025-10-02 01:36

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('BILL_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('BILL_TYPE', models.CharField(choices=[('Power', 'Power'), ('Gas', 'Gas'), ('Water', 'Water')], max_length=10)),
                ('TIMESTAMP_UPLOAD', models.DateTimeField(auto_now_add=True)),
                ('BILL_DATE', models.DateField()),
                ('UNITS_OF_MEASURE', models.CharField(max_length=32)),
                ('CONSUMPTION', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('SERVICE_START', models.DateField(blank=True, null=True)),
                ('SERVICE_END', models.DateField()),
                ('PROVIDER', models.CharField(max_length=128)),
                ('CITY', models.CharField(max_length=128)),
                ('STATE', models.CharField(max_length=2)),
                ('ZIP', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='ZIP must be 5 digits', regex='^\\d{5}$')])),
                ('COST', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('FILE_SOURCE', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
