# Generated by Django 5.2.7 on 2025-10-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_type', models.CharField(choices=[('Power', 'Power'), ('Gas', 'Gas'), ('Water', 'Water')], max_length=20)),
                ('timestamp_upload', models.DateTimeField(blank=True, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('units_of_measure', models.CharField(blank=True, choices=[('kWh', 'kWh'), ('therms', 'therms'), ('CCF', 'CCF')], max_length=8, null=True)),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('service_start', models.DateField(blank=True, null=True)),
                ('service_end', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=8, null=True)),
                ('zip', models.CharField(blank=True, max_length=16, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('file_source', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['-bill_date'],
                'indexes': [models.Index(fields=['bill_date'], name='SustainSync_bill_da_43ea56_idx'), models.Index(fields=['provider'], name='SustainSync_provide_8ccc59_idx'), models.Index(fields=['city', 'state'], name='SustainSync_city_bf38ba_idx')],
            },
        ),
    ]
