# Generated by Django 5.2.7 on 2025-10-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SustainSync', '0003_sustainabilitygoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sustainabilitygoal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sustainability Goal', 'verbose_name_plural': 'Sustainability Goals'},
        ),
        migrations.AlterField(
            model_name='sustainabilitygoal',
            name='target_date',
            field=models.DateField(blank=True, help_text='Target completion date', null=True),
        ),
    ]
