# Generated by Django 5.2.7 on 2025-11-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SustainSync', '0004_alter_sustainabilitygoal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('kWh', 'kWh'), ('therms', 'therms'), ('CCF', 'CCF'), ('gallons', 'gallons')], max_length=10, null=True),
        ),
    ]
