# Generated by Django 5.2.7 on 2025-11-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SustainSync', '0005_alter_bill_units_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainabilitygoal',
            name='analysis_type',
            field=models.CharField(choices=[('goals', 'Goals-Focused (2 recommendations per goal)'), ('co-benefit', 'Co-Benefit Analysis (cross-utility synergies)'), ('environmental', 'Environmental Impact (carbon & ecological focus)')], default='goals', help_text='Type of analysis to perform for this goal', max_length=20),
        ),
    ]
